version: "2"

services:
  ca.org1.example.com:
    container_name: ca.org1.example.com
    extends:
      file: base/ca-base.yaml
      service: ca-base
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
      - ORGANIZATION_DOMAIN=org1.example.com
    ports:
      - "7054:7054"
    volumes:
      - ./base/fabric-ca-server-template.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-template.yaml
      - ./ca/org1/:/etc/hyperledger/fabric-ca-server/